import type { Metadata } from "next";
import { Funnel_Sans } from "next/font/google";
import Header from "@/components/header/Header";

import "bootstrap/dist/css/bootstrap.min.css";
import '../styles/globals.css'

const funnelSans = Funnel_Sans({
  subsets: ['latin'],
  variable: '--font-funnel'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${funnelSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
