import type { Metadata } from "next";
import { Funnel_Sans } from "next/font/google";
import Header from "@/components/header/Header";
import WipeOnScroll from "@/components/common/WipeOnScroll";
import RouteBodyClass from "@/components/common/RouteBodyClass";

import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "@/components/footer/Footer";
import Script from "next/script";
import ScrollToTop from "@/components/common/ScrollToTop";
import '../styles/globals.css'
import Providers from "@/lib/Providers";

const funnelSans = Funnel_Sans({
  subsets: ['latin'],
  variable: '--font-funnel'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${funnelSans.variable} h-full antialiased`}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <RouteBodyClass />
        <WipeOnScroll />
        <Providers>
        <Header />
        {children}
        <Footer />
        <ScrollToTop />
        <Script src="/js/smoothscroll.min.js" strategy="lazyOnload" />
        </Providers>
      </body>
    </html>
  );
}
